include themes/matugen.conf
window_padding_width 5
hide_window_decorations yes
background_opacity 0.8
# font_family FiraCode Nerd Font Mono Bold
font_family Iosevka Bold
font_size 24
remember_window_size no
confirm_os_window_close 0
shell /usr/bin/fish
# shell /usr/bin/zsh
cursor_trail 1 
cursor_shape block
shell_integration no-cursor

# tab bar
tab_bar_edge                top
tab_bar_style               powerline
tab_powerline_style         slanted
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style round
tab_bar_min_tabs 1
tab_title_max_length 5
tab_bar_margin_width 2
tab_separator       ""
tab_title_template " [{index}] {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab} {title}"

map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9


# BEGIN_KITTY_THEME
# Matugen
include current-theme.conf
# END_KITTY_THEME
