# ---- METADATA ----
# 参考了 https://github.com/Hentioe/dotfiles/blob/master/keyd/61.conf
# https://blog.hentioe.dev/posts/advanced-keymapping-keyd-tutorial.html
# Target: /etc/keyd/61.conf
# Author: khanif
# CreatedAt: 2026-6-19
# UpdatedAt: 2026-06-19
# ---- METADATA ----

[ids]
# USB HID x3
# 352d:2380
0001:0001

[global]
chord_timeout = 40

[main]
# Caps 扩展层
capslock = overload(layercap, oneshot(shift))
# Esc 扩展层
esc = overload(layeresc, esc)
# Tab 扩展层
tab = overload(layertab, tab)

[layercap]
# 模拟游戏方向键
h = left
j = down
l = right
k = up
u = home
d = end
e = esc
# 翻页操作
p = pageup
n = pagedown
# 退格/删除键两用
# backspace = delete
# 反引号
# esc = `
# 右功能键
# minus = f11
# equal = f12
# 常用操作
c = macro( C-c )
x = macro( C-x )
v = macro( C-v )
z = macro( C-z )
# 生成引号对
# apostrophe = macro( " " left )
# 生成括号对
# 9 = macro( ( ) left )
# 生成中括号对
# [ = macro( [ ] left )

[layeresc]
# 左功能键
# 1 = f1
# 2 = f2
# 3 = f3

[layertab]
# KDE 工作区切换
# q = macro( C-A-left )
# e = macro( C-A-right )

[shift]
# 波浪号
# esc = ~
