# ---- METADATA ----
# https://github.com/Hentioe/dotfiles/blob/master/keyd/61.conf
# https://blog.hentioe.dev/posts/advanced-keymapping-keyd-tutorial.html
# Target: /etc/keyd/61.conf
# Author: Hentioe (绅士喵)
# CreatedAt: 2026-03-27
# UpdatedAt: 2026-04-03
# ---- METADATA ----

[ids]
# USB HID x3
352d:2380

[global]
chord_timeout = 40

[main]
# Caps 扩展层
capslock = overload(layercap, oneshot(shift))
# Esc 扩展层
esc = overload(layeresc, esc)
# Tab 扩展层
tab = overload(layertab, tab)
# 字母组合键退格
d+f = backspace
# 字母组合键删除
j+k = delete

[layercap]
# 模拟游戏方向键
a = left
s = down
d = right
w = up
# 翻页操作
compose = pagedown
slash = pageup
# 退格/删除键两用
backspace = delete
# 反引号
esc = `
# 右功能键
minus = f11
equal = f12
# 常用操作
c = macro( C-c )
x = macro( C-x )
v = macro( C-v )
z = macro( C-z )
# 生成引号对
apostrophe = macro( " " left )
# 生成括号对
9 = macro( ( ) left )
# 生成中括号对
[ = macro( [ ] left )

[layeresc]
# 左功能键
1 = f1
2 = f2
3 = f3

[layertab]
# KDE 工作区切换
q = macro( C-A-left )
e = macro( C-A-right )

[shift]
# 波浪号
esc = ~
