include custom/themes/matugen.conf
window_padding_width 5
hide_window_decorations yes
background_opacity 0.8

remember_window_size no
confirm_os_window_close 0
# shell /usr/bin/fish
# shell /usr/bin/zsh
cursor_trail 1 
cursor_shape block
shell_integration no-cursor

# tab bar
tab_bar_edge                top
tab_bar_style               powerline
tab_powerline_style         slanted
tab_bar_min_tabs 1
tab_title_max_length 5
tab_bar_margin_width 2
tab_separator       ""
tab_title_template " [{index}] {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab} {title}"

map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9

# Dracula Color Scheme
# background #282a36
# foreground #f8f8f2
# cursor #f8f8f2
# selection_background #44475a
# selection_foreground #f8f8f2

# Normal colors
# color0 #000000
# color1 #ff5555
# color2 #50fa7b
# color3 #f1fa8c
# color4 #bd93f9
# color5 #ff79c6
# color6 #8be9fd
# color7 #bfbfbf
# color8 #4d4d4d
# color9 #ff6e67
# color10 #5af78e
# color11 #f4f99d
# color12 #caa9fa
# color13 #ff92d0
# color14 #9aedfe
# color15 #e6e6e6

# Cursor
# cursor_text_color #282a36

# window
# hide_window_decorations        titlebar-only
hide_window_decorations        on
window_padding_width           15
# window_padding_width           24
background_opacity             0.75
# background_blur                64
remember_window_size           yes

# Dark
# foreground              #d3d7cf
# active_tab_foreground   #d3d7cf
# active_tab_background   #2e3436
active_tab_font_style   normal
# inactive_tab_foreground #d3d7cf
# inactive_tab_background #222222
# tab_bar_background      #222222
# tab_bar_margin_color    #222222

# BEGIN_KITTY_THEME
# Matugen
include current-theme.conf
# END_KITTY_THEME

# font_family FiraCode Nerd Font Mono Bold
font_family Iosevka
font_size 22

# BEGIN_KITTY_FONTS
# font_family      family="Iosevka Nerd Font"
# bold_font        family="Iosevka Nerd Font Bold"
# italic_font      auto
# bold_italic_font auto
# END_KITTY_FONTS
